"use client";
import { Metadata } from "next";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: {
//     absolute: "",
//     default: "Default value from main layout",
//     template: "%s | Varun",
//   },
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [input, setinput] = useState("");
  const router = useRouter();
  const handleClick = () => {
    router.forward();
  };
  return (
    <div>
      <div style={{ display: "flex", gap: "20px" }}>
        <Link href="/blog/first">first</Link>
        <Link href={{ pathname: "/blog/1", query: { title: "static query" } }}>
          Dynamic 1
        </Link>
        <Link href="/blog/second">second</Link>
        <button onClick={handleClick}>Click</button>
        <input value={input} onChange={(e) => setinput(e.target.value)} />
      </div>

      {children}
    </div>
  );
}
