export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (Math.floor(Math.random() * 2) === 1) {
    throw new Error("Error while loading product!");
  }

  return <div> 1213{children}</div>;
}
